version: 0.2
 
phases:
  install:
    commands:
      - echo Installing Terraform 1.14.3
      - curl -O https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
      - unzip terraform_1.14.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
 
  pre_build:
    commands:
      - echo Initializing Terraform
      - terraform init
 
  build:
    commands:
      - echo Running Terraform plan
      - terraform plan -out=tfplan
 
  post_build:
    commands:
      - echo Applying Terraform
      - terraform apply -auto-approve tfplan
 
artifacts:
  files:
    - '**/*'
