version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      # Install unzip if not present
      - sudo yum install -y unzip
      # Download specific Terraform version (v1.14.3)
      - TF_VERSION="1.14.3"
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      # Unzip and move to global path
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      # Initialize without remote backend
      - terraform init -input=false
  build:
    commands:
      - terraform plan -out=tfplan -input=false
  post_build:
    commands:
      - terraform apply -auto-approve tfplan
