version: 0.2

phases:
  install:
    commands:
      - echo "Detecting architecture and installing Terraform..."
      - sudo yum install -y unzip wget
      - TF_VERSION="1.14.3"
      # Detect if system is x86_64 (amd64) or aarch64 (arm64)
      - ARCH=$(uname -m)
      - if [ "$ARCH" = "x86_64" ]; then TF_ARCH="amd64"; else TF_ARCH="arm64"; fi
      - echo "Downloading Terraform v${TF_VERSION} for ${TF_ARCH}..."
      - wget releases.hashicorp.com{TF_VERSION}/terraform_${TF_VERSION}_linux_${TF_ARCH}.zip
      - unzip terraform_${TF_VERSION}_linux_${TF_ARCH}.zip
      - sudo mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      - echo "Initializing with S3 Backend..."
      # Replace these with your actual S3 bucket details
      - terraform init -input=false \
          -backend-config="bucket=your-terraform-state-bucket-name" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=us-east-1"
  build:
    commands:
      - terraform plan -out=tfplan -input=false
  post_build:
    commands:
      - echo "Applying changes..."
      - terraform apply -auto-approve tfplan
